Python download
Tamir-M/package-installer pull request #25
Opened 2023-02-22 20:29 UTC by Vamqueror

added selection for package type (npm or pip)
added pip download option (downloads to output)

2023-02-23 17:15 UTC, Tamir-M requested changes
Great work, just look at the comments I've added, I like how you handled it.

2023-02-23 17:15 UTC, Tamir-M commented on util/files.py
> +    version_info = response_body["releases"][version][0]
Instead of getting version `[0]` try to look for the `tar.gz` file if it exists, and maybe only if it doesn't, fall back to `[0]` index.
We are trying to get the packages to be uploaded to a local mirror.

Look at `pygame` as an example of an input, it'll download the mac version? although I'm on windows, and my program will probably look for a `tar.gz` to be uploaded later?

2023-02-23 18:14 UTC, Vamqueror commented on util/files.py
> +    version_info = response_body["releases"][version][0]
Bad assumption by me, I assumed that the windows version would always be on [0].

I will fix it when i come back from the priel incident.

Btw, what do you think is more suitable for this use-case?:
Downloading the file according to the user's OS
Or
Adding an OS selection menu
Or
Always download the windows version

2023-02-24 08:14 UTC, Tamir-M commented on util/files.py
> +    version_info = response_body["releases"][version][0]
Actually, I'd rather you download the `source distribution`, as the `build distributions` are used for specific OS's, and with the source ones, you can always build your version correctly.
They are usually `tar.gz` files as I've mentioned above.
If that doesn't exist, you can fall back into any option you'd like. (person's OS or maybe give them an option).
But the focus of this program is to be able to download a package into a remote mirror of `pip` or `npm`, so a `source distribution` would be a better fit.

2023-02-28 19:04 UTC, Vamqueror commented on util/files.py
> +    version = latest_stable_release(releases)
What a blunder. I didn't see that it was included in the response. Will fix

2023-02-28 19:48 UTC, Vamqueror commented
The current version includes a TODO comment that provides context on how to extend the feature and totally complete. I will probably do it on a separate PR (Most popular libraries includes a source distribution so I wanted to ship the feature with this limitation for now)

2023-03-01 06:30 UTC, Tamir-M approved these changes
Nice work!

2023-03-01 06:31 UTC, merged